package com.dragonmeow.nyanlex.forgelegacy;

import com.dragonmeow.nyanlex.translate.HookHealth;

/** forge1132: 24 guarded hooks (generated by verification/hook-guards.py - do not edit by hand). */
public final class NyanLexHooks {
    private NyanLexHooks() {
    }

    /** Registers every guarded hook id; call once from the loader entry point.
     *  Sinks may be null (falls back to java.util.logging). */
    public static void register(java.util.function.Consumer<String> info,
            java.util.function.Consumer<String> warn) {
        HookHealth.setSinks(info, warn);
        HookHealth.expectAmbient(
            "event.onOverlayPost",
            "event.onOverlayText");
        HookHealth.expect(
            "event.afterScreen",
            "event.beforeScreen",
            "event.closed",
            "event.drag",
            "event.draw",
            "event.init",
            "event.key",
            "event.mouse",
            "event.onChat",
            "event.onClientCommand",
            "event.onClientTick",
            "event.onInitGui",
            "event.onNameTagPost",
            "event.onNameTagPre",
            "event.onTooltipRender",
            "event.release",
            "event.released",
            "event.screenKey",
            "event.screenKeyReleased",
            "event.scroll",
            "event.typed",
            "hook.translateScreenString");
    }
}
