package com.dragonmeow.nyanslate.forgelegacy;

import com.dragonmeow.nyanslate.translate.HookHealth;

/** forge1132: 12 guarded hooks (generated by verification/hook-guards.py - do not edit by hand). */
public final class NyanslateHooks {
    private NyanslateHooks() {
    }

    /** Registers every guarded hook id; call once from the loader entry point.
     *  Sinks may be null (falls back to java.util.logging). */
    public static void register(java.util.function.Consumer<String> info,
            java.util.function.Consumer<String> warn) {
        HookHealth.setSinks(info, warn);
        HookHealth.expectAmbient(
            "event.onOverlayPost",
            "event.onOverlayText");
        HookHealth.expect(
            "event.afterScreen",
            "event.beforeScreen",
            "event.onChat",
            "event.onClientTick",
            "event.onNameTagPost",
            "event.onNameTagPre",
            "event.onTooltipRender",
            "event.screenKey",
            "event.screenKeyReleased",
            "hook.translateScreenString");
    }
}
