plugins {
    id 'fabric-loom' version "${loom_version}"
    id 'java'
}
version = project.mod_version
group = project.maven_group
base { archivesName = project.archives_base_name }
tasks.named('remapJar') { archiveClassifier = "Fabric-${project.minecraft_version}" }
tasks.named('jar') {
    from('../LICENSE') { rename { 'LICENSE_MinecraftTranslator' } }
}
repositories {
    mavenCentral()
    maven { url = 'https://maven.fabricmc.net/' }
}
dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 21
}
processResources {
    inputs.property 'version', project.version
    filesMatching('fabric.mod.json') { expand 'version': project.version }
}
test { useJUnitPlatform() }
sourceSets.test.java.exclude '**/FabricTextStyleIntegrationTest.java'
