package com.dragonmeow.nyanlex.legacy;

import com.dragonmeow.nyanlex.translate.HookHealth;

/** fabric1152: 21 guarded hooks (generated by verification/hook-guards.py - do not edit by hand). */
public final class NyanLexHooks {
    private NyanLexHooks() {
    }

    /** Registers every guarded hook id; call once from the loader entry point.
     *  Sinks may be null (falls back to java.util.logging). */
    public static void register(java.util.function.Consumer<String> info,
            java.util.function.Consumer<String> warn) {
        HookHealth.setSinks(info, warn);
        HookHealth.expectAmbient(
            "DebugHud.debug");
        HookHealth.expect(
            "ChatComponent.translate",
            "ChatComposer.chatEdited",
            "ChatComposer.clickComposer",
            "ChatComposer.closeComposer",
            "ChatComposer.initComposer",
            "ChatComposer.keyComposer",
            "ChatComposer.renderComposer",
            "ChatComposer.scrollComposer",
            "EntityNameTag.begin",
            "EntityNameTag.end",
            "EntityNameTag.name",
            "FontText.draw",
            "FontText.shadow",
            "FontText.split",
            "OptionsScreen.addButton",
            "ScreenKey.screenKey",
            "ScreenRenderScope.afterScreenRender",
            "ScreenRenderScope.beforeScreenRender",
            "event.clientTick",
            "event.itemTooltip");
    }
}
