package com.dragonmeow.nyanlex.fabric;

import com.dragonmeow.nyanlex.translate.HookHealth;

/** fabric120: 38 guarded hooks (generated by verification/hook-guards.py - do not edit by hand). */
public final class NyanLexHooks {
    private NyanLexHooks() {
    }

    /** Registers every guarded hook id; call once from the loader entry point.
     *  Sinks may be null (falls back to java.util.logging). */
    public static void register(java.util.function.Consumer<String> info,
            java.util.function.Consumer<String> warn) {
        HookHealth.setSinks(info, warn);
        HookHealth.expectAmbient(
            "ChatComponent.enterChatRender",
            "ChatComponent.exitChatRender",
            "DebugHud.debug");
        HookHealth.expect(
            "BookPage.forceResplit",
            "BookPage.translateBookPage",
            "BossBar.bossBar",
            "ChatComposer.chatEdited",
            "ChatComposer.clickComposer",
            "ChatComposer.closeComposer",
            "ChatComposer.initComposer",
            "ChatComposer.keyComposer",
            "ChatComposer.renderComposer",
            "ChatComposer.scrollComposer",
            "EntityNameTag.stackedNameTag",
            "EntityNameTag.translateNameTag",
            "FontSplit.translateBeforeTrim",
            "FontSplit.translateBeforeWrap",
            "GuiGraphicsText.screenTextCentered",
            "GuiGraphicsText.screenTextComponent",
            "GuiGraphicsText.screenTextOrdered",
            "GuiGraphicsText.screenTextString",
            "GuiGraphicsText.visibleComponentTooltip",
            "GuiGraphicsText.visibleTooltip",
            "GuiScoreboard.clearScoreboard",
            "GuiScoreboard.heldName",
            "GuiScoreboard.inlineHud",
            "GuiScoreboard.prepareScoreboard",
            "GuiScoreboard.scoreboard",
            "OptionsScreen.addToggle",
            "TextField.translateWhole",
            "event.allowChat",
            "event.allowGame",
            "event.clientTick",
            "event.itemTooltip",
            "event.screenAfterRender",
            "event.screenBeforeRender",
            "event.screenKey",
            "event.warmupHud");
    }
}
