modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mixins]]
config = "nyanlex.neoforge.mixins.json"

[[mods]]
logoFile="icon.png"
modId = "nyanlex"
version = "${version}"
displayName = "NyanLex Translator"
description = "Client-side translation into multiple target languages with OpenAI-compatible AI or machine translation (an unofficial Google endpoint). Unofficial: not affiliated with or endorsed by Mojang, Microsoft, Hypixel or any mod author."
authors = "DragonMeow"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.nyanlex]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.nyanlex]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "CLIENT"
