modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mixins]]
config = "mctranslator.neoforge.mixins.json"

[[mods]]
modId = "mctranslator"
version = "${version}"
displayName = "Minecraft Translator"
description = "Client-side translation into multiple target languages with OpenAI-compatible AI or Google, Youdao, DeepL, and Microsoft machine translation."
authors = "DragonMeow"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.mctranslator]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.mctranslator]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "CLIENT"
