package com.dragonmeow.nyanlex.fabric;

import com.dragonmeow.nyanlex.translate.HookHealth;

/** fabric1182: 29 guarded hooks (generated by verification/hook-guards.py - do not edit by hand). */
public final class NyanLexHooks {
    private NyanLexHooks() {
    }

    /** Registers every guarded hook id; call once from the loader entry point.
     *  Sinks may be null (falls back to java.util.logging). */
    public static void register(java.util.function.Consumer<String> info,
            java.util.function.Consumer<String> warn) {
        HookHealth.setSinks(info, warn);
        HookHealth.expectAmbient(
            "DebugHud.debug");
        HookHealth.expect(
            "BookPage.page",
            "BookPage.resplit",
            "BossBar.boss",
            "ChatComponent.translateLegacyChat",
            "ChatComposer.chatEdited",
            "ChatComposer.clickComposer",
            "ChatComposer.closeComposer",
            "ChatComposer.initComposer",
            "ChatComposer.keyComposer",
            "ChatComposer.renderComposer",
            "ChatComposer.scrollComposer",
            "EntityNameTag.stackedNameTag",
            "EntityNameTag.translateNameTag",
            "FontSplit.translateBeforeTrim",
            "FontSplit.translateBeforeWrap",
            "GuiScoreboard.clear",
            "GuiScoreboard.held",
            "GuiScoreboard.hud",
            "GuiScoreboard.prepare",
            "GuiScoreboard.score",
            "OptionsScreen.addToggle",
            "TextField.translateWhole",
            "event.clientTick",
            "event.itemTooltip",
            "event.screenAfterRender",
            "event.screenBeforeRender",
            "event.screenKey",
            "event.warmupHud");
    }
}
