package com.dragonmeow.nyanlex.neoforge;

import com.dragonmeow.nyanlex.translate.HookHealth;

/** neoforge: 36 guarded hooks (generated by verification/hook-guards.py - do not edit by hand). */
public final class NyanLexHooks {
    private NyanLexHooks() {
    }

    /** Registers every guarded hook id; call once from the loader entry point.
     *  Sinks may be null (falls back to java.util.logging). */
    public static void register(java.util.function.Consumer<String> info,
            java.util.function.Consumer<String> warn) {
        HookHealth.setSinks(info, warn);
        HookHealth.expectAmbient(
            "ChatComponent.enterChatRender",
            "ChatComponent.exitChatRender",
            "DebugHud.debug");
        HookHealth.expect(
            "BookPage.forceResplit",
            "BookPage.translateBookPage",
            "BossBar.bossBar",
            "EntityNameTag.stackedNameTag",
            "FontSplit.translateBeforeTrim",
            "FontSplit.translateBeforeWrap",
            "GuiGraphicsText.screenTextCentered",
            "GuiGraphicsText.screenTextComponent",
            "GuiGraphicsText.screenTextOrdered",
            "GuiGraphicsText.screenTextString",
            "GuiGraphicsText.visibleComponentTooltip",
            "GuiGraphicsText.visibleTooltip",
            "GuiScoreboard.actionBar",
            "GuiScoreboard.clearScoreboard",
            "GuiScoreboard.heldName",
            "GuiScoreboard.prepareScoreboard",
            "GuiScoreboard.scoreboard",
            "GuiScoreboard.title",
            "OptionsScreen.addToggle",
            "TextField.translateWhole",
            "event.onClientChat",
            "event.onClientTick",
            "event.onConsentKeyPress",
            "event.onConsentKeyRelease",
            "event.onConsentMouseClick",
            "event.onConsentMouseRelease",
            "event.onConsentMouseScroll",
            "event.onItemTooltip",
            "event.onRenderNameTag",
            "event.onScreenKeyPressed",
            "event.onScreenRenderPost",
            "event.onScreenRenderPre",
            "event.warmupHud");
    }
}
