modLoader="javafml"
loaderVersion="[25,)"

[[mods]]
logoFile="icon.png"
modId="nyanslate"
version="${file.jarVersion}"
displayName="Nyanslate"
authors="DragonMeow"
description='''Client-side translation into multiple target languages with OpenAI-compatible AI or Google, Youdao, DeepL, and Microsoft machine translation.'''

[[dependencies.nyanslate]]
modId="forge"
mandatory=true
versionRange="[25,)"
ordering="NONE"
side="CLIENT"

[[dependencies.nyanslate]]
modId="minecraft"
mandatory=true
versionRange="[1.13.2]"
ordering="NONE"
side="CLIENT"
