package com.dragonmeow.nyanslate.fabric26;

import com.dragonmeow.nyanslate.translate.HookHealth;

/** fabric2612: 25 guarded hooks (generated by verification/hook-guards.py - do not edit by hand). */
public final class NyanslateHooks {
    private NyanslateHooks() {
    }

    /** Registers every guarded hook id; call once from the loader entry point.
     *  Sinks may be null (falls back to java.util.logging). */
    public static void register(java.util.function.Consumer<String> info,
            java.util.function.Consumer<String> warn) {
        HookHealth.setSinks(info, warn);
        HookHealth.expectAmbient(
            "Hud.debugRequests");
        HookHealth.expect(
            "BookPage.forceResplit",
            "BookPage.translateBookPage",
            "BossBar.bossBar",
            "EntityNameTag.captureState",
            "EntityNameTag.name",
            "FontSplit.translateBeforeWrap",
            "GuiGraphicsText.screenTextComponent",
            "GuiGraphicsText.screenTextString",
            "Hud.actionBar",
            "Hud.clearScoreboard",
            "Hud.heldName",
            "Hud.prepareScoreboard",
            "Hud.scoreboard",
            "Hud.title",
            "OptionsScreen.addButton",
            "ScreenRenderScope.beginVisibleScreen",
            "ScreenRenderScope.endVisibleScreen",
            "TextField.translateWhole",
            "event.allowChat",
            "event.allowGame",
            "event.clientTick",
            "event.itemTooltip",
            "event.screenKey",
            "event.warmupHud");
    }
}
