package com.dragonmeow.nyanlex.neoforge26;

import com.dragonmeow.nyanlex.translate.HookHealth;

/** neoforge26: 24 guarded hooks (generated by verification/hook-guards.py - do not edit by hand). */
public final class NyanLexHooks {
    private NyanLexHooks() {
    }

    /** Registers every guarded hook id; call once from the loader entry point.
     *  Sinks may be null (falls back to java.util.logging). */
    public static void register(java.util.function.Consumer<String> info,
            java.util.function.Consumer<String> warn) {
        HookHealth.setSinks(info, warn);
        HookHealth.expectAmbient(
            "Hud.debugRequests");
        HookHealth.expect(
            "BookPage.forceResplit",
            "BookPage.translateBookPage",
            "BossBar.bossBar",
            "EntityNameTag.captureState",
            "EntityNameTag.name",
            "FontSplit.translateBeforeTrim",
            "FontSplit.translateBeforeWrap",
            "GuiGraphicsText.screenTextComponent",
            "GuiGraphicsText.screenTextString",
            "Hud.actionBar",
            "Hud.clearScoreboard",
            "Hud.heldName",
            "Hud.prepareScoreboard",
            "Hud.scoreboard",
            "Hud.title",
            "OptionsScreen.addButton",
            "TextField.translateWhole",
            "event.onClientChat",
            "event.onClientTick",
            "event.onItemTooltip",
            "event.onScreenKeyPressed",
            "event.onScreenRenderPost",
            "event.onScreenRenderPre");
    }
}
