package com.dragonmeow.nyanslate.fabric;

import com.dragonmeow.nyanslate.translate.HookHealth;

/** fabric1182: 20 guarded hooks (generated by verification/hook-guards.py - do not edit by hand). */
public final class NyanslateHooks {
    private NyanslateHooks() {
    }

    /** Registers every guarded hook id; call once from the loader entry point.
     *  Sinks may be null (falls back to java.util.logging). */
    public static void register(java.util.function.Consumer<String> info,
            java.util.function.Consumer<String> warn) {
        HookHealth.setSinks(info, warn);
        HookHealth.expectAmbient(
            "DebugHud.debug");
        HookHealth.expect(
            "BookPage.page",
            "BookPage.resplit",
            "BossBar.boss",
            "ChatComponent.translateLegacyChat",
            "EntityNameTag.stackedNameTag",
            "EntityNameTag.translateNameTag",
            "FontSplit.translateBeforeWrap",
            "GuiScoreboard.clear",
            "GuiScoreboard.held",
            "GuiScoreboard.hud",
            "GuiScoreboard.prepare",
            "GuiScoreboard.score",
            "OptionsScreen.addToggle",
            "TextField.translateWhole",
            "event.clientTick",
            "event.itemTooltip",
            "event.screenAfterRender",
            "event.screenBeforeRender",
            "event.screenKey");
    }
}
